"""Update Match

Revision ID: 6c9a8a874a41
Revises: add22e5d798a
Create Date: 2025-12-21 09:35:27.551884

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c9a8a874a41"
down_revision: Union[str, None] = "add22e5d798a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match_request", sa.Column("iteration", sa.Integer(), nullable=False))
    op.add_column("match_request", sa.Column("match_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "match_request", "match", ["match_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match_request", type_="foreignkey")
    op.drop_column("match_request", "match_id")
    op.drop_column("match_request", "iteration")
    # ### end Alembic commands ###
