"""Update User

Revision ID: a1f5993501d9
Revises: ee68e017c505
Create Date: 2025-12-14 10:19:18.886980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f5993501d9'
down_revision: Union[str, None] = 'ee68e017c505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('clan_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('clan_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'clan_tag')
    op.drop_column('user', 'clan_name')
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
