"""Init schema

Revision ID: add22e5d798a
Revises:
Create Date: 2025-12-16 20:18:28.413785

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add22e5d798a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("ranked", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CREATED", "ACCEPTED", "REJECTED", "COMPLETED", "CANCELED", name="matchstatus"),
            nullable=False,
        ),
        sa.Column(
            "map",
            sa.Enum(
                "TEN_THOUSAND_FEET",
                "CELESTIAL_ENCLAVE",
                "MOTHERSHIP",
                "OLD_REPUBLIC",
                "RUBY_ROCK",
                "TAITO_CITADEL",
                "TOURMALINE",
                "WHITE_RABBIT",
                "WINTER_MADNESS",
                name="laddermaps",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("battle_tag", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("clan_name", sa.String(), nullable=True),
        sa.Column("clan_tag", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("email", name="user_unique_constraint"),
    )
    op.create_table(
        "match_association_table",
        sa.Column("match_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.create_table(
        "match_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("ranked", sa.Boolean(), nullable=False),
        sa.Column("matchups", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "status", sa.Enum("CREATED", "PENDING", "FULFILLED", "CANCELED", name="matchrequeststatus"), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_rating",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "matchup",
            sa.Enum(
                "ZVT",
                "ZVP",
                "ZVZ",
                "ZVR",
                "TVT",
                "TVP",
                "TVZ",
                "TVR",
                "PVT",
                "PVP",
                "PVZ",
                "PVR",
                "RVT",
                "RVP",
                "RVZ",
                "RVR",
                name="matchup",
            ),
            nullable=False,
        ),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "matchup", "rating", "created_at", name="user_mmr_unique_constraint"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_rating")
    op.drop_table("match_request")
    op.drop_table("match_association_table")
    op.drop_table("user")
    op.drop_table("match")
    # ### end Alembic commands ###
