"""Add MatchRequest model

Revision ID: d1b634fc9f00
Revises: a1f5993501d9
Create Date: 2025-12-14 15:09:07.359785

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1b634fc9f00"
down_revision: Union[str, None] = "a1f5993501d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("ranked", sa.Boolean(), nullable=False),
        sa.Column("matchups", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CREATED", "PENDING", "FULFILLED", "CANCELED", name="matchrequeststatus"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_table("match_request")
    # ### end Alembic commands ###
